apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-content-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7Gi
  storageClassName: standard-dynamic
